title: Nathan Kane
tagline: Product engineering
bio: I'm a product engineer focused on building for the web, currently at a freight transportation startup called Transfix. Previously, I worked at the Clinton campaign and Intuit.
email: hi@nathanrkane.com
description: > # this means to ignore newlines until "baseurl:"
  The front-end engineering and product design
  blog of Nathan Kane, a front-end developer and designer. I write about what I learn
  building UX with Javascript.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kanenathan213.github.io" # the base hostname & protocol for your site
twitter_username: uibiquity
github_username:  kanenathan213
dribbble_username:  kanenathan213
collections:
  projects:
    output: true
    permalink: /:path/
permalink: "/writing/:title"
# Build settings
markdown: kramdown
