title: Nathan Kane
tagline: Product engineering
bio: I'm a product-focused software engineering leader. I love using Python, React, and Node to solve big problems.
email: hi@nathanrkane.com
description: > # this means to ignore newlines until "baseurl:"
  My personal site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kanenathan213.github.io" # the base hostname & protocol for your site
twitter_username: kanenathan213
github_username:  kanenathan213
dribbble_username:  kanenathan213
collections:
  projects:
    output: true
    permalink: /:path/
permalink: "/writing/:title"
# Build settings
markdown: kramdown
